language: java
env:
  - ACTIVATOR_VERSION=1.3.2 \
    ACTIVATOR_ZIP_FILE=typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip \
    ACTIVATOR_ZIP_URL=http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/${ACTIVATOR_ZIP_FILE} \
    ACTIVATOR_BIN=${TRAVIS_BUILD_DIR}/activator-${ACTIVATOR_VERSION}-minimal/activator \
    H2_VERSION=1.4.187 \
    H2_JAR_URL=http://central.maven.org/maven2/com/h2database/h2/${H2_VERSION}/h2-${H2_VERSION}.jar
install:
  - wget ${ACTIVATOR_ZIP_URL}
  - unzip -q ${ACTIVATOR_ZIP_FILE}
  - wget ${H2_JAR_URL}
before_script:
  - "java -jar h2-${H2_VERSION}.jar &"
script:
  - "${ACTIVATOR_BIN} flywayMigrate"
  - "${ACTIVATOR_BIN} test"
after_script:
  - "pkill 'jar h2'"
notifications:
  # Email notifications are disabled to not annoy anybody.
  email: false
